# Generated by Django 5.1.7 on 2025-03-20 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='private_key',
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='public_key',
            field=models.BinaryField(null=True),
        ),
    ]
